In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('result/results.csv')

In [4]:
df

,Unnamed: 0,threshold_0.5 (1),threshold_0.95 (1),threshold_0.5 (2),threshold_0.95 (2),threshold_0.5 (3),threshold_0.95 (3),threshold_0.5 (4),threshold_0.95 (4),threshold_0.5 (5),...,threshold_0.5 (all),threshold_0.95 (all),name,mAP (all),mAP (seg),mAP (text),mAP (title),mAP (list),mAP (table),mAP (figure)
0,0,0.621071,0.589679,0.629973,0.620147,0.440435,0.391068,0.714833,0.701500,0.501274,...,0.774002,0.703541,count_gnn_1,0.211324,0.554277,0.482075,0.252274,0.024188,0.062480,0.235603
1,1,0.546287,0.507636,0.665620,0.662525,0.376495,0.339073,0.760667,0.727000,0.566917,...,0.768162,0.691056,count_gnn_2,0.213560,0.540699,0.364724,0.302746,0.038319,0.132472,0.229540
2,2,0.707171,0.683720,0.665828,0.664578,0.501555,0.455012,0.752667,0.744333,0.574444,...,0.785814,0.730055,count_gnn_3,0.269814,0.568862,0.545929,0.298132,0.022880,0.161573,0.320555
3,3,0.729264,0.699486,0.688042,0.680288,0.530776,0.488382,0.702500,0.697500,0.515000,...,0.784822,0.713337,count_gnn_4,0.230864,0.556730,0.576319,0.320126,0.035776,0.027723,0.194376

      threshold_0.5 (all)  threshold_0.95 (all)  mAP (all)  mAP (seg)
mean             0.770299              0.700966   0.249565   0.547529
std              0.013148              0.017638   0.038340   0.020052
min              0.754930              0.676862   0.178721   0.523238
max              0.801011              0.741010   0.299258   0.587129